---

- name: install EPEL repository
  yum: name=epel-release state=present
  when: >  # not for Fedora
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Red Hat Enterprise Linux'
  become: yes

- name: install python2 psycopg2
  yum:
    name:
      - python-psycopg2
      - sudo
      - wget
      - perl
    state: present

- name: install python3 psycopg2
  yum:
    name:
      - python3-psycopg2
      - sudo
      - wget
      - perl
    state: present

- name: fixup some locale issues
  lineinfile:
    dest: /etc/default/locale
    line: 'LANGUAGE="{{ item }}"'
    state: present
    create: yes
  loop:
    - 'en_US:en'
    - 'en_us.UTF-8'

- name: config postgres repository
  vars:
    base: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-"
    os_major_ver: "{{ ansible_facts['distribution_major_version'] }}"
    arch: "{{ ansible_facts['architecture'] }}"
  yum:
    name: "{{ base }}{{ os_major_ver }}-{{ arch }}/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
  become: yes

- name: install postgres packages
  yum:
    name:
      - postgresql{{ postgres_server_pkg_version }}-server
    state: present
  become: yes
