---
- name: make kube config dir
  file:
    path: ~/.kube
    state: directory

- name: copy kube config file
  copy:
    src: files/kube-config
    dest: ~/.kube/config

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab Runner is already installed.
  stat:
    path: "/usr/bin/gitlab-runner"
  register: gitlab_runner_file

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_runner_repository_installation_script_url }}"
    dest: /tmp/gitlab_runner_install_repository.sh
    validate_certs: "{{ gitlab_runner_download_validate_certs }}"
  when: gitlab_runner_file.stat.exists == false

- name: Install GitLab Runner repository.
  command: bash /tmp/gitlab_runner_install_repository.sh
  when: gitlab_runner_file.stat.exists == false

- name: Define the Gitlab Runner package name.
  set_fact:
    gitlab_runner_package_name: "{{ gitlab_runner_base_package_name }}{{ gitlab_runner_package_version_separator }}{{ gitlab_runner_version }}"
  when: gitlab_runner_version != ''

- name: Install GitLab Runner.
  package:
    name: "{{ gitlab_runner_package_name | default(gitlab_runner_base_package_name) }}"
    state: installed
  when: gitlab_runner_file.stat.exists == false

- name: Create the Gitlab Runner configuration directory.
  file:
    path: "{{ gitlab_runner_conf_dir }}"
    state: directory
    owner: "{{ gitlab_runner_conf_dir_owner }}"
    group: "{{ gitlab_runner_conf_dir_group }}"
    mode: "{{ gitlab_runner_conf_dir_mode }}"

- name: Deregister all runners.
  shell: >
    gitlab-runner unregister --all-runners
  become: yes

- name: Verify all runners deleted.
  shell: >
    gitlab-runner verify --delete
  become: yes

- name: Register new runners using the gitlab-runner command.
  shell: >
    gitlab-runner register --non-interactive
    --url "{{ item.url | default(gitlab_runner_coordinator_url) }}"
    --registration-token {{ item.token | default(gitlab_runner_token) }}
    --name "{{ item.name }}"
    --tag-list "{{ item.tags }}"
    {% if item.builds_dir | default('') != '' %}
    --builds-dir {{ item.builds_dir }}
    {% endif %}
    {% if item.executor == "docker" %}
    --executor docker
    --docker-image "docker:19.03.12"
    --docker-privileged 
    --docker-volumes "/etc/docker/daemon.json:/etc/docker/daemon.json"
    --docker-volumes "/root/.docker:/root/.docker"
    --docker-volumes "/root/.kube:/root/.kube"
    {% endif %}
    {% if item.executor == "shell" %}
    --executor shell
    --shell bash
    {% endif %}
  with_items: "{{ gitlab_runners }}"
  become: yes
